spring:
  application:
    name: preguntonic
    
  output:
    ansi:
      enabled: always

  # Database (h2)
  datasource:
    url: jdbc:h2:mem:preguntonic
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

# Debug Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
